Repository wintercms/docs, pull requests merged in 2024-10, with the labels that each got.

#210 Add options to `create:job` command
  console/scaffolding.md
Labels: Type: Maintenance, Status: Completed

#176 Docs for Laravel style relations
  database/relations.md
  database/traits.md
Labels: Status: Completed, Type: Enhancement

#216 Document how to dynamically add a custom list column type
  backend/lists.md
Labels: Type: Maintenance, Status: Completed

#170 Add example of Mail::fake() for unit testing in docs
  services/mail.md
Labels: Type: Maintenance

#213 Document npm:* commands
  console/asset-compilation.md
  console/asset-node-utilities.md
Labels: Status: Completed, Type: Enhancement
