Repository wintercms/docs, pull requests merged in 2024-07, with the labels that each got.

#196 Add single/double quote recommendations
  architecture/developer-guide.md
Labels: Type: Maintenance, Status: Completed

#197 Add information on withoutMiddleware and rate limit throttling
  services/router.md
Labels: Type: Maintenance, Status: Completed

#201 Document Asset Priority
  services/asset-compilation.md
Labels: Type: Enhancement

#200 Added vite documentation and split out mix from asset compilation
  console/asset-compilation-mix.md
  console/asset-compilation-vite.md
  console/asset-compilation.md
Labels: Status: Completed, Type: Enhancement

#163 Add notes for the scheduler setup
  setup/installation.md
Labels: Type: Maintenance, Status: Completed
